import { demoArticleBody } from "./article-body";
import { postSchema, type Post } from "./schemas";

const SERVING_SERIES = { slug: "serving-llms-cheaply", title: "Serving LLMs cheaply" } as const;

export const posts: Post[] = postSchema.array().parse([
  {
    slug: "speculative-decoding-measured",
    title: "Speculative decoding, measured: where the 2.3× actually comes from",
    dek: "Acceptance rate explains less of the speedup than everyone assumes. Batch shape explains more.",
    topic: "Inference",
    publishedAt: "2026-08-12",
    readingMinutes: 11,
    likes: 412,
    views: 18400,
    commentCount: 26,
    tags: ["#inference", "#benchmarks", "#cuda", "#serving"],
    series: { ...SERVING_SERIES, part: 2 },
    body: demoArticleBody,
  },
  {
    slug: "why-our-rag-evaluation-kept-lying-to-us",
    title: "Why our RAG evaluation kept lying to us",
    dek: "Four months of green dashboards, one broken retrieval index, and the eval design that hid it.",
    topic: "Evaluation",
    publishedAt: "2026-07-29",
    readingMinutes: 9,
    likes: 388,
    views: 16100,
    commentCount: 41,
    tags: ["#evaluation", "#rag", "#reproducibility"],
    body: demoArticleBody,
  },
  {
    slug: "reading-the-flashattention-3-kernel",
    title: "Reading the FlashAttention-3 kernel line by line",
    dek: "A guided tour of the tiling, the warp specialisation, and the parts I still don't fully follow.",
    topic: "Systems",
    publishedAt: "2026-07-14",
    readingMinutes: 17,
    likes: 521,
    views: 22700,
    commentCount: 33,
    tags: ["#cuda", "#serving"],
    body: demoArticleBody,
  },
  {
    slug: "a-type-level-dsl-for-feature-flags",
    title: "A type-level DSL for feature flags",
    dek: "Making impossible flag combinations unrepresentable, with about sixty lines of TypeScript.",
    topic: "Engineering",
    publishedAt: "2026-06-30",
    readingMinutes: 8,
    likes: 264,
    views: 11200,
    commentCount: 19,
    tags: ["#typescript"],
    body: demoArticleBody,
  },
  {
    slug: "quantization-at-4-bits-what-breaks-first",
    title: "Quantization at 4 bits: what breaks first",
    dek: "Per-task degradation curves for six open models. Reasoning goes before summarisation, every time.",
    topic: "Inference",
    publishedAt: "2026-06-11",
    readingMinutes: 12,
    likes: 349,
    views: 14800,
    commentCount: 22,
    tags: ["#quantization", "#benchmarks", "#inference"],
    body: demoArticleBody,
  },
  {
    slug: "postgres-index-bloat-quantified",
    title: "Postgres index bloat, quantified",
    dek: "We reclaimed 340 GB and 40% of p99 latency. Here's how the bloat accumulated in the first place.",
    topic: "Engineering",
    publishedAt: "2026-05-27",
    readingMinutes: 10,
    likes: 297,
    views: 13500,
    commentCount: 28,
    tags: ["#postgres"],
    body: demoArticleBody,
  },
  {
    slug: "training-a-340m-model-on-one-gpu",
    title: "Training a 340M model on one GPU for $40",
    dek: "A weekend budget run: data mixture, curriculum, and every step where I wasted money.",
    topic: "Experiments",
    publishedAt: "2026-05-08",
    readingMinutes: 14,
    likes: 433,
    views: 19600,
    commentCount: 37,
    tags: ["#benchmarks", "#distillation"],
    body: demoArticleBody,
  },
  {
    slug: "notes-on-tokenizer-edge-cases",
    title: "Notes on tokenizer edge cases",
    dek: "Whitespace, emoji joiners, and the silent truncation that cost us two days of debugging.",
    topic: "Findings",
    publishedAt: "2026-04-22",
    readingMinutes: 6,
    likes: 186,
    views: 8900,
    commentCount: 12,
    tags: ["#tokenizers"],
    body: demoArticleBody,
  },
  {
    slug: "serving-embeddings-without-a-vector-database",
    title: "Serving embeddings without a vector database",
    dek: "At 4M vectors, a memory-mapped index and a single Postgres table beat the managed service.",
    topic: "Systems",
    publishedAt: "2026-04-03",
    readingMinutes: 11,
    likes: 312,
    views: 15300,
    commentCount: 24,
    tags: ["#postgres", "#serving", "#rag"],
    body: demoArticleBody,
  },
  {
    slug: "the-eval-harness-i-actually-trust",
    title: "The eval harness I actually trust",
    dek: "Deterministic seeds, held-out slices, and refusing to look at aggregate scores first.",
    topic: "Evaluation",
    publishedAt: "2026-03-19",
    readingMinutes: 9,
    likes: 275,
    views: 12400,
    commentCount: 17,
    tags: ["#evaluation", "#reproducibility"],
    body: demoArticleBody,
  },
  {
    slug: "distillation-beat-pruning-on-our-task",
    title: "Distillation beat pruning on our task",
    dek: "Same latency budget, 3.1 points better. The result that made me stop pruning altogether.",
    topic: "Experiments",
    publishedAt: "2026-03-02",
    readingMinutes: 8,
    likes: 241,
    views: 10700,
    commentCount: 15,
    tags: ["#distillation", "#benchmarks"],
    body: demoArticleBody,
  },
  {
    slug: "reproducing-a-paper-that-didnt-reproduce",
    title: "Reproducing a paper that didn't reproduce",
    dek: "Three weeks, two emails to the authors, and a correction that changed the headline number.",
    topic: "Research",
    publishedAt: "2026-02-14",
    readingMinutes: 13,
    likes: 366,
    views: 17200,
    commentCount: 44,
    tags: ["#reproducibility", "#evaluation"],
    body: demoArticleBody,
  },
] satisfies Post[]);
